---
title: "Midterm Project - GitHub"
subtitle: "JSC370 (Winter 2026)"
format:
  html:
    toc: true
    embed-resources: true
jupyter: python3
execute:
  enabled: true
  echo: false
  warning: false
  message: false
---

### Github [https://github.com/Richard098789/JSC370/tree/main/final_project](link)

# Introduction
Online job postings provide valuable insights into labour market demand and skills. As a data science student currently looking for a job, I am interested in **how do role type, location, and job characteristics relate to salary levels in Canadian data-related job postings? Does salary increase over time?**. 

In this project, job posting data were collected using the Adzuna Job Search API, which collects job listings from multiple job boards and company career pages. Each job posting contains information such as the job title, company name, location, salary range, contract type, and description. These attributes make the dataset suitable for exploratory data analysis, as it includes a mix of numerical, binary and categorical variables.

The goal of this project is to explore patterns in salary levels across different job characteristics. In particular, the analysis focuses on comparing salaries across major data-related roles such as data scientists, data engineers, and data analysts, as well as examining geographic differences across Canadian regions. Additional exploratory analysis investigates whether the of job posting date is associated with variations in salary levels.

# Method

### 1. Data Collection
- Use Adzuna Job Search API to collect job postings data. Restrict the search range to Canada and the job title to include "data". Convert the data into a pandas dataframe. Fetch the first num_pages pages of data, with 50 jobs per page.
```{python}
import requests
import pandas as pd

APP_ID = "d34356b4"
APP_KEY = "90420aa2d69109d0658ba473fbae9572"

jobs = []
num_pages = 80

for page in range(1, num_pages):

    url = f"https://api.adzuna.com/v1/api/jobs/ca/search/{page}"

    params = {
        "app_id": APP_ID,
        "app_key": APP_KEY,
        "what": "data",
        "results_per_page": 50
    }

    response = requests.get(url, params=params)
    data = response.json()

    for job in data["results"]:
        jobs.append({
    "title": job.get("title"),
    "company": job.get("company", {}).get("display_name"),
    "location": job.get("location", {}).get("display_name"),
    "salary_min": job.get("salary_min"),
    "salary_max": job.get("salary_max"),
    "contract_type": job.get("contract_type"),
    "category": job.get("category", {}).get("label"),
    "created": job.get("created")
})

df = pd.DataFrame(jobs)

```

- Collected 3750 job postings, with features: title, company, location, salary_min, salary_max, contract_type, category, created.

### 2. Data Cleaning
1. Check and remove missing values.
```{python}
df_clean = df.dropna(subset=[
    "title",
    "company",
    "location",
    "salary_min",
    "salary_max",
    "category"
])
```

2. Remove parentheses and punctuation from the job title.
```{python}
import re

df_clean["title_clean"] = (
    df_clean["title"]
    .str.lower()
    .str.replace(r"\(.*?\)", "", regex=True)
    .str.replace(r"[^a-z\s]", "", regex=True)
    .str.strip()
)
```

3. Filter the data to only include the job titles that contain the keywords "engineer", "scientist", "analyst", or "architect".
```{python}
keywords = ["engineer", "scientist", "analyst", "architect"]

df_clean = df_clean[df_clean["title_clean"].str.contains("|".join(keywords), na=False)]
```

4. Classify the job titles into four categories: Data Scientist, Data Analyst, Data Engineer, and Other.
```{python}
def classify_role(title):

    if "scientist" in title:
        return "Data Scientist"

    if "analyst" in title:
        return "Data Analyst"

    if "engineer" in title or "architect" in title:
        return "Data Engineer"

    return "Other"

df_clean["role"] = df_clean["title_clean"].apply(classify_role)
```

5. Calculate the median salary for each role.
```{python}
df_clean["salary_mid"] = (
    df_clean["salary_min"] + df_clean["salary_max"]
) / 2
```

6. map the contract type to a binary variable: 1 for permanent and 0 for contract.
```{python}
df_clean["is_permanent"] = df_clean["contract_type"].map({
    "permanent": 1,
    "contract": 0
})
```

7. Clean the location column. Add a location map to convert the location to province.
```{python}
df_clean["location_clean"] = df_clean["location"].str.lower().str.strip()
def get_province(loc):

    if pd.isna(loc):
        return None

    loc = loc.lower()

    # Ontario
    if any(x in loc for x in [
        "ontario", "toronto", "markham", "mississauga", "north york",
        "guelph", "oakville", "oshawa", "pickering", "concord",
        "woodbridge", "halton", "durham", "york region",
        "waterloo region", "ottawa", "peel region"
    ]):
        return "Ontario"

    # British Columbia
    if any(x in loc for x in [
        "british columbia", "vancouver", "victoria", "abbotsford",
        "revelstoke", "fraser valley", "saanichton", "fort st. john"
    ]):
        return "British Columbia"

    # Quebec
    if any(x in loc for x in [
        "québec", "quebec", "montreal", "montréal"
    ]):
        return "Quebec"

    # Alberta
    if any(x in loc for x in [
        "alberta", "calgary", "edmonton"
    ]):
        return "Alberta"

    # Manitoba
    if any(x in loc for x in [
        "manitoba", "virden", "winnipeg"
    ]):
        return "Manitoba"

    # Nova Scotia
    if any(x in loc for x in [
        "nova scotia", "halifax"
    ]):
        return "Nova Scotia"

    # New Brunswick
    if any(x in loc for x in [
        "new brunswick", "saint john", "moncton"
    ]):
        return "New Brunswick"

    # If only Canada is given
    if "canada" in loc:
        return "Unknown"

    return "Other"
df_clean["province"] = df_clean["location_clean"].apply(get_province)
```

8. Categorize the salary into low, medium, and high.
```{python}
df_clean["salary_level"] = pd.cut(
    df_clean["salary_mid"],
    bins=[0, 80000, 120000, 200000],
    labels=["Low", "Medium", "High"]
)
```

9. Convert the created date to datetime.
```{python}
df_clean["created"] = pd.to_datetime(df_clean["created"])
df_clean["date"] = df_clean["created"].dt.date
```


# Preliminary Results

### 0. Basic Summary Statistics
```{python}
n_jobs = len(df_clean)
n_roles = df_clean["role"].nunique()
n_provinces = df_clean["province"].nunique()
date_min = df_clean["created"].min()
date_max = df_clean["created"].max()
```

The cleaned dataset contains 371 job postings related to data-focused roles across 9 Canadian provinces. These postings are grouped into 3 primary job role categories, including Data Scientist, Data Analyst, and Data Engineer. The job postings are collected from 2024-07-30 to 2026-03-13. Most jobs are posted in the past 6 months.


### 1. Salary Distribution
```{python}
salary_summary = df_clean["salary_mid"].describe()
salary_summary
```

Visualize the distribution of the salary midpoints.
```{python}
import seaborn as sns
import matplotlib.pyplot as plt
sns.histplot(df_clean["salary_mid"], bins=30)
plt.title("Distribution of Advertised Salary Midpoints")
plt.xlabel("Salary Midpoint")
plt.ylabel("Number of Job Postings")
```

Figure shows the distribution of salary midpoint values. Most job postings fall within a middle salary range, while a smaller number of postings list substantially higher salaries.

### 2. Salary Distribution by Job Role
```{python}
role_salary = df_clean.groupby("role")["salary_mid"].agg(
    ["count","mean","median","std"]
).round(0)

role_salary
```

```{python}
sns.boxplot(data=df_clean, x="role", y="salary_mid")
plt.title("Salary Distribution by Job Role")
plt.xlabel("Job Role")
plt.ylabel("Salary Midpoint")
```

Figure compares salary distributions across job roles. Data Engineer has highest salary, then Data Scientist roles, with Data Analyst roles having the lowest salary. Data Enguneer also has a high variance in salary.

### 3. Number of Job Postings by Job Role
```{python}
sns.countplot(data=df_clean, x="role")
plt.title("Number of Job Postings by Role")
plt.xlabel("Job Role")
plt.ylabel("Number of Job Postings")
```

Figure shows the number of job postings by job role. Data Engineer has the most job postings, followed by Data Analyst, and Data Scientist has the least job postings.

### 4. Salary Distribution by Contract Type
```{python}
sns.boxplot(data=df_clean, x="is_permanent", y="salary_mid")
plt.title("Salary Distribution by Contract Type")
plt.xlabel("Contract Type")
plt.ylabel("Salary Midpoint")
```

Figure shows the salary distribution by contract type. Permanent contracts have around same salary compared to contract jobs. (~100000)

### 5. Salary Distribution by Province

```{python}
province_salary = (
    df_clean
    .dropna(subset=["salary_mid"])
    .groupby("province")["salary_mid"]
    .agg(count="count", mean="mean", median="median", std="std")
    .round(0)
    .reset_index()
)

province_salary.style.format({
    "mean": "${:,.0f}",
    "median": "${:,.0f}",
    "std": "${:,.0f}"
})

province_salary
```

```{python}
sns.boxplot(data=df_clean, x="province", y="salary_mid")
plt.title("Salary Distribution by Province")
plt.xlabel("Province")
plt.ylabel("Salary Midpoint")
plt.xticks(rotation=20)
```

Figure shows the salary distribution by province. Jobs with region not posted in Canada has the highest salary, followed by Ontario, Quebec, and Manitoba, Nova Scotia, New Brunswick have lower salary.

### 6. Average salary by posting date and job role

```{python}
jobs_by_date = df_clean.groupby("date").size().reset_index(name="count")
plt.figure()

sns.lineplot(data=jobs_by_date, x="date", y="count")

plt.title("Number of Job Postings Over Time")
plt.xlabel("Posting Date")
plt.ylabel("Number of Jobs")
plt.xticks(rotation=45)
```

```{python}
salary_date_role = (
    df_clean
    .dropna(subset=["salary_mid"])
    .groupby(["date", "role"])["salary_mid"]
    .mean()
    .reset_index()
)
plt.figure()

sns.lineplot(
    data=salary_date_role,
    x="date",
    y="salary_mid",
    hue="role"
)

plt.title("Average Salary by Posting Date and Job Role")
plt.xlabel("Posting Date")
plt.ylabel("Average Salary Midpoint")
plt.xticks(rotation=45)
```

Figure shows a salary trend by posting date and job role. All 3 roles have similar salary trend, with a slight increase in salary over time.


# Summary

After cleaning and processing the data, the analysis would focus on several key features including job role, location, contract type and created date.

The exploratory analysis revealed several preliminary patterns in the dataset. First, salary distributions differ across job roles. Positions categorized as Data Engineer and Data Scientist generally have higher salary ranges compared to Data Analyst roles. 

Second, the geographic distribution of job postings is uneven across Canada. A large proportion of postings in the dataset are located in Ontario, while smaller numbers appear in provinces such as British Columbia, Quebec, and Alberta. Salary distributions also vary across provinces, although the number of observations in some regions is relatively small. These geographic differences suggest that regional job markets may influence salary levels.

Third, the temporal trend analysis shows that average salary have been increasing over time since 2024, with a slight decrease in 2025. Since most job fetched are from recent time, if more job postings are collected from older time, we can further investigate the trend.

# Plan

First, I wll expand the data size by fetching more job postings using Adzuna API to include more job postings from older time. This would help learn more about the trend of salary over time.

Next I will use ML methods to further explore the relationship between salary and other features. As an initial baseline, a linear regression model will be fitted to estimate salary based on features such as job role, geographic location, contract type, and posting date. To capture potential nonlinear relationships, models such as GAM will also be used. Finally, ensemble learning methods including random forests and gradient boosting will be used to improve predictive performance and identify the most important factors influencing salary.

I would focus on exploring role type, and whether different months of a year have different salary levels. I would also focus on exploring region and compare them with actual Canadian geographic boundaries to better understand regional job market patterns.

The result of the model will be added to interactive website, where user can pick the features they are interested in and see the predicted salary. 